const js = require("@eslint/js");
const tseslint = require("@typescript-eslint/eslint-plugin");
const prettier = require("eslint-config-prettier");

/**
 * ESLint 9 flat config. Replaces the old .eslintrc.js (which extended a
 * monorepo-parent config that no longer exists). Standard stack: JS recommended
 * + typescript-eslint recommended, with eslint-config-prettier last to turn off
 * stylistic rules that Prettier owns.
 */
module.exports = [
  // Generated by `wrangler types` — not ours to lint.
  { ignores: ["worker-configuration.d.ts"] },
  js.configs.recommended,
  ...tseslint.configs["flat/recommended"],
  prettier,
];
